baseURL = 'https://hyurii1024.github.io/homepage/'
languageCode = 'en-us'
title = 'HYURIi no homepage'
theme = 'PaperMod'
publishDir = "docs"
defaultContentLanguage = 'ja'

[languages]
  [languages.ja]
    languageCode = 'ja-JP'
    languageDirection = 'ltr'
    languageName = 'Japanese'
    weight = 1
    

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[params]
  env = "production"  # これがあるとOGタグ出力されます
  title = "HYURIiのホームページ"
  description = "イラストとBlender練習中の記録"
  images = ["images/caticon.png"]  # OGP画像（相対パス。static/images内に置く）
  customCSS = ["css/custom.css"]
[params.profileMode]
  enabled = true
  title = "ヒュリー/HYURIi"
  subtitle = "イラストとBlender練習中です"
  imageUrl = "images/teacaticon.png"  # 画像ファイルは static/images に置く
  imageWidth = 160              # 表示サイズ（px）
  imageHeight = 160
  imageTitle = "ヒュリーのアイコン"

[[params.socialIcons]]
name = "pixiv"
url = "https://www.pixiv.net/users/64404057"
[[params.socialIcons]]
  name = "x"
  url = "https://x.com/sakenikomi"